FROM ruby:3.0.1
ENV BUNDLER_VERSION=2.2.15

RUN gem install bundler -v 2.2.15

RUN mkdir /referral_tracker
WORKDIR /referral_tracker

EXPOSE 3000

COPY Gemfile Gemfile.lock ./

RUN bundle check || bundle install

CMD ["/bin/sh"]
